[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
bevy_networking_turbulence = { git = "https://github.com/berlingoqc/bevy_networking_turbulence/", branch="master", default-features = false, features = ["use-webrtc"] }
bevy = { version = "0.7.0", default-features = false }
